language: node_js
node_js:
 - '8'
install:
 - yarn install
 - yarn build
 - yarn add $WEBPACK $TSLOADER $VUELOADER -D
env:
 - WEBPACK=webpack@^4.0.0 TSLOADER=ts-loader@^4.3.0 VUELOADER=vue-loader@^15.2.4
 - WEBPACK=webpack@^3.10.0 TSLOADER=ts-loader@^3.4.0 VUELOADER=vue-loader@^13.5.0
 - WEBPACK=webpack@^2.7.0 TSLOADER=ts-loader@^3.4.0 VUELOADER=vue-loader@^13.5.0
deploy:
  provider: npm
  email: piotrek.oles@gmail.com
  skip_cleanup: true
  api_key:
    secure: CBqE7TbznvJn5/rkRPdzF3QH4mrkt7pGp/v9H5jk1RQrdL29+zeCPGMe8WsFnpJWBwM6NDzQDnR4FzPTzg9AIF/pE2Q+EA8wRJdMiDgqLcWBgNTrbyFKi8qSvWEKpaUwbfmyeIGjmaeCCY/UIrBFcOwq7Uuo5owBMBKOrGTeu14JK4ZvhB2H4Kn/SjzPKxaUm2epcwzhZTjVlzjMWlsKMiXnBtOHoTW2HirnqO0rtRtCdZQR3Bsvkg7RTLI+P3zmCjl6C+fSS50NCfIVZq1Hz9MUIzjhuofhqoL1u8BYZMz23uUYnkn95tpyi8ZJl40kXGnDhT0bEHVuD4V+noLG+z9EJp0wj+fTtD4kz6OrIQe73tjuZ5psdmqcYNG4yRgwldnpjVWQ//6UBBWtFKd4NOudHs67q8KeQDjVBY/Yw/qbKtvYxpuilMCqvN2nLvxSCu8kaOWw3QXUJLRZbrYsN/iRlBglDDNecMrswXXnNVKWsjR6wzWkDladQwcBrqBzcizBbItqQjCG+/D4i8nHmiw/lg18lwBD9RxtMsVdJhJQdoSYR+S3DROqVGurxOk3vDA/z+Z+RRVA0v2oGaS5iLnSGXTSSK+Weri5RRdTaCeL+nnSF+zsoA6wtsZpwdhzZRM/l0dzJhcH5XPMEQZNLFEsss2/d54rPBqAC8acJUk=
  on:
    tags: true
    branch: master
